### PR TITLE
Feat/flag migration

### PR DESCRIPTION
**Pull request by skhamvon**

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#987.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build#1049.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build#1049.1 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build#1058.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build-storybook#1060.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build-storybook#1060.1 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build#1072.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build#1077.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build-storybook#1092.0 ✘  
* 
  * build ✘

**Review by dpellier — CHANGES_REQUESTED** [review]
You did commit numerous outdated generated folders, please delete the following:
- packages-new/components/icon/custom-elements-bundle
- packages-new/components/icon/custom-elements
- packages-new/components/icon/loader/
- packages-new/components/icon/react/src
- packages-new/components/icon/vue/src
- packages/stencil/components/menu
- packages/stencil/components/text
- packages/stencil/components/textarea

**Comment by ovh-cds** [comment]
CDS Report build#1142.0 ■   
* 
  * build ■

**Comment by ovh-cds** [comment]
CDS Report build#1142.0 ■   
* 
  * build ■

**Comment by skhamvon** [comment]
New PR : https://github.com/ovh/design-system/pull/146

**Pull request closed without merging**
