### PR TITLE
Feat/new archi - move OsdsText & OsdsTextarea

### PR DESCRIPTION
**Pull request by dpellier**
⚠ BREAKING CHANGES ⚠
- OsdsText is no longer part of `@ovhcloud/ods-stencil` package
- OsdsTextarea is no longer part of `@ovhcloud/ods-stencil` package
- OsdsText is now accessible by adding either `ods-component-text` or `ods-components` dependencies
- OsdsTextarea is now accessible by adding either `ods-component-textarea` or `ods-components` dependencies
- `@ovhcloud/ods-stencil-text` lib has been replace by `@ovhcloud/ods-component-text`
- `@ovhcloud/ods-stencil-text-react` lib has been replace by `@ovhcloud/ods-component-text-react`
- `@ovhcloud/ods-stencil-text-vue` lib has been replace by `@ovhcloud/ods-component-text- vue`
- `@ovhcloud/ods-stencil-textarea` lib has been replace by `@ovhcloud/ods-component-textarea`
- `@ovhcloud/ods-stencil-textarea-react` lib has been replace by `@ovhcloud/ods-component-textarea-react`
- `@ovhcloud/ods-stencil-textarea-vue` lib has been replace by `@ovhcloud/ods-component-textarea- vue`
- `OdsTextSize` has been removed from `@ovhcloud/ods-core` and is replaced by `ODS_TEXT_SIZE` from `@ovhcloud/ods-component-text`
- `OdsTextSizeList` has been removed from `@ovhcloud/ods-core` and is replaced by `ODS_TEXT_SIZES` from `@ovhcloud/ods-component-text`
- `OdsTextSizeUnion` has been removed from `@ovhcloud/ods-core`
- `OdsTextAreaSize` has been removed from `@ovhcloud/ods-core` and is replaced by `ODS_TEXTAREA_SIZE` from `@ovhcloud/ods-component-textarea`
- `OdsTextAreaSizeList` has been removed from `@ovhcloud/ods-core` and is replaced by `ODS_TEXTAREA_SIZES` from `@ovhcloud/ods-component-textarea`
- `OdsTextAreaSizeUnion` has been removed from `@ovhcloud/ods-core`
- OsdsTextarea is now displayed as flex by default
- OsdsTextarea `flex` attribute has been removed
- OsdsTextarea `inline` attribute has been added

⚠? BREAKING CHANGES ?⚠ (in theory, those methods should be internal and not usable by integrators)
- `odsCamelCase2KebabCase` method has been moved to `ods-common-testing`
- `OdsComponentAttributes2StringAttributes` method has been renamed `odsComponentAttributes2StringAttributes` and has been moved to `ods-common-testing`
- `OdsStringAttributes2Str` method has been renamed `odsStringAttributes2Str` and has been moved to `ods-common-testing`

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#856.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build-storybook#860.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build-storybook#862.0 ✘  
* 
  * build ✘

**Review by aesteves60 — APPROVED** [review]

**Review by astagnol — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build#992.0 ✘  
* 
  * build ✘

**Pull request merged**
