### PR TITLE
feat(arch): move && simplify component popover

### PR DESCRIPTION
**Pull request by dpellier**
⚠ BREAKING CHANGES ⚠
- OsdsPopover is no longer part of `@ovhcloud/ods-stencil` package
- OsdsPopover is now accessible by adding either `ods-component-popover` or `ods-components` dependencies
- `@ovhcloud/ods-component-popover` lib has been replaced by `@ovhcloud/ods-component-popover`
- `@ovhcloud/ods-component-popover-react` lib has been replaced by `@ovhcloud/ods-component-popover-react`
- `@ovhcloud/ods-component-popover-vue` lib has been replaced by `@ovhcloud/ods-component-popover- vue`

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-storybook#1241.0 ✘  
* 
  * build ✘

**Review by Leotheluck — CHANGES_REQUESTED** [review]
there are bits of code from progress-bar

**Review by feoche — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build#1247.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build#1248.0 ✘  
* 
  * build ✘

**Review by Leotheluck — APPROVED** [review]

**Review by aesteves60 — APPROVED** [review]

**Pull request merged**
