### PR TITLE
fix(accordion): dont open when disabled

### PR DESCRIPTION
**Pull request by skhamvon**
- Fix accordion that was opening even when it was disabled

### CODE REVIEW

**Review by aesteves60 — APPROVED** [review]

**Review by aesteves60 — CHANGES_REQUESTED** [review]
Need test

**Review by aesteves60 — APPROVED** [review]

**Review by astagnol — CHANGES_REQUESTED** [review]
Working but pending since we need a final check about this fix with design team.
And I think it could be nice to add 'disabled' in Storybook controls

**Review by dpellier — CHANGES_REQUESTED** [review]
can you add a `disable` control on stroybook for this component?

**Review by dpellier — CHANGES_REQUESTED** [review]
Disabled accordion is still focusable, is it the expected behaviour?

**Review by dpellier — APPROVED** [review]

**Review by aesteves60 — APPROVED** [review]

**Review by astagnol — APPROVED** [review]

**Pull request merged**
