### PR TITLE
fix(button): remove margin & padding of host

### PR DESCRIPTION
**Pull request by skhamvon**
Remove margin & padding to prevent click event outside of the component

### CODE REVIEW

**Review by dpellier — CHANGES_REQUESTED** [review]
I've tried the React example and was abli to click the disabled button on Chromium and Safari

**Review by aesteves60 — CHANGES_REQUESTED** [review]
We need a test that has failed before the fix

**Review by astagnol — CHANGES_REQUESTED** [review]
Same here, I am able to click when disabled on several browsers (react example):
Firefox (123.0.1) -> can click just a few pixels outside the disabled button (but ok on the border)
Safari (Version 17.3.1 ) -> same
Chromium (Version 112.0.5615.49) -> can click on the disabled button (button, border, a few pixels outside of it)

**Review by Leotheluck — APPROVED** [review]

**Review by aesteves60 — APPROVED** [review]

**Review by dpellier — CHANGES_REQUESTED** [review]
Still possible to call an attached click event listener on chromium.

What you can do, is add an inert prop on the host, like:
```
<Host ...
        inert: this.disabled
```

**Comment by dpellier** [comment]
There is an issue with Chromium and `slot` content in a `disabled` element (see: https://issues.chromium.org/issues/40679491#comment13)
Issue is reproductible on other framework too.
A workaround could be to "silence" the slot using something like:
Capture d’écran 2024-04-02 à 15 05 55

Please give it a try following the whole process:
- reproduce the issue on your local Chromium
- apply the fix
- test on Chromium / FF / Safari (/ Edge)

**Review by feoche — APPROVED** [review]

**Pull request merged**
