### PR TITLE
Feat/collapsible

### PR DESCRIPTION
**Pull request by aesteves60**

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-storybook#526.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build-storybook#525.0 ✘  
* 
  * build ✘

**Review by ady642 — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-storybook#542.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build-storybook#542.1 ✘  
* 
  * build ✘

**Review by astagnol — APPROVED** [review]

**Review by astagnol — APPROVED** [review]

**Pull request merged**
